# Generated by Django 3.2.12 on 2022-02-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
